[workspace]
resolver = "3"
members = [
  "kernel",
  "drivers/hello",
  "drivers/char",
#  "test"
]
[workspace.dependencies]
kernel = { path = "kernel"}



[profile.release]
panic="abort"
lto = true

[profile.dev]
panic="abort"
lto = true

